creacion/urls.py
from django.urls import path 
  
# importing views from views..py 
from .views import detail_view, delete_view, list_view, update_view,create_view, creacion_json
  
app_name='crud'

urlpatterns = [ 
    path('creacion',create_view,name="create"),
    path('',list_view,name="list"),
    
    path('update/<id>',update_view,name="update"),
    path('detail/<id>', detail_view,name="detail" ), 
    path('delete/<id>', delete_view,name="delete" ),
    path('creacion_json', creacion_json,name="creacion_json" ),
] 

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('creacion.urls',namespace='crud'))

]

creacion/models.py
# import the standard Django Model 
# from built-in library 
from django.db import models 
   
# declare a new model with a name "GeeksModel" 
class GeeksModel(models.Model): 
  
    # fields of the model 
    title = models.CharField(max_length = 200) 
    description = models.TextField() 
  
    # renames the instances of the model 
    # with their title name 
    def __str__(self): 
        return self.title 

creacion/forms.py
from django import forms 
from .models import GeeksModel 
  
  
# creating a form 
class GeeksForm(forms.ModelForm): 
  
    # create meta class 
    class Meta: 
        # specify model to be used 
        model = GeeksModel 
  
        # specify fields to be used 
        fields = [ 
            "title", 
            "description", 
        ] 

creacion/views.py
from django.shortcuts import (get_object_or_404, 
                              render, 
                              HttpResponseRedirect, redirect) 
# relative import of forms 
from .models import GeeksModel 
from .forms import GeeksForm 
from django.http import JsonResponse

def creacion_json(request):
    # add the dictionary during initialization 
    if request.method == "POST":
        titulo = request.POST["titulo"]
        description = request.POST["descripcion"]
        geek = GeeksModel.objects.create(title=titulo,description=description)
        geek.save()
        respuesta =["Creacion de contenido"]
    return JsonResponse(respuesta,safe=False)  
    
def create_view(request): 
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
    
  
    # add the dictionary during initialization 
    if request.method == "POST":
        titulo = request.POST["titulo"]
        description = request.POST["descripcion"]
        geek = GeeksModel.objects.create(title=titulo,description=description)
        geek.save()
        return redirect("/")
          
    
    return render(request, "create_view.html", context) 

def list_view(request): 
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
  
    # add the dictionary during initialization 
    context["dataset"] = GeeksModel.objects.all() 
          
    return render(request, "list_view.html", context) 

# pass id attribute from urls 
def detail_view(request, id): 
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
  
    # add the dictionary during initialization 
    context["data"] = GeeksModel.objects.get(id = id) 
          
    return render(request, "detail_view.html", context) 

# update view for details 
def update_view(request, id): 
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
  
    # fetch the object related to passed id 
    obj = get_object_or_404(GeeksModel, id = id) 
  
    # pass the object as instance in form 
    if request.method == "POST":
        titulo = request.POST["titulo"]
        description = request.POST["descripcion"]
        obj.title = titulo
        obj.description = description
        obj.save()
        return redirect("/"+"detail/"+id) 
  
    # add form dictionary to context 
    context["titulo"] = obj.title
    context["descripcion"] = obj.description

  
    return render(request, "update_view.html", context) 


# delete view for details 
def delete_view(request, id): 
    # dictionary for initial data with  
    # field names as keys 
    context ={} 
  
    # fetch the object related to passed id 
    obj = get_object_or_404(GeeksModel, id = id) 
  
  
    if request.method =="POST": 
        # delete object 
        obj.delete() 
        # after deleting redirect to  
        # home page 
        return HttpResponseRedirect("/") 
  
    return render(request, "delete_view.html", context) 

creacion/templates/create_view.html
{% load static %}
<link rel="stylesheet" href="{% static 'css.css' %}">
<form action="/creacion_json" method="POST" id="myForm" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    <div>
        <label for="Title">titulo </label>
        <input id="Title" name="titulo"
        class="jsvalidator" 
        data-validators="required"
        type="text">
    </div>
    <div>
        <label for="descripcion">descripción </label>
        <input id="descripcion" name="descripcion" data-validators="required" type="text">
    </div>

      
    <input type="submit" value="Submit"> 
</form> 

<script src="{% static 'jsvalidator.js' %}"></script>

<script>

    const myFormValidator = new JSValidator('myForm').init().setAjax();
    


</script>

creacion/templates/delete_view.html
<div class="main"> 
    <!-- Create a Form -->
    <form method="POST"> 
        <!-- Security token by Django -->
        {% csrf_token %} 
        Are you want to delete this item ? 
        <input type="submit" value="Yes" /> 
        <a href="/">Cancel </a> 
    </form> 
</div> 

creacion/templates/detail_view.html
<div class="main"> 
      <button><a href="/">regresar</a></button><br>
    

    <!-- Specify fields to be displayed -->
    {{ data.title }}<br/> 
    {{ data.description }}<br/> 
  

    <button><a href="{% url 'crud:update' data.id %}">Update</a></button>
    <button><a href="{% url 'crud:delete' data.id %}">Delete</a></button>
</div> 

creacion/templates/list_view.html
<div class="main"> 
    <a href='{% url "crud:create" %}'>Creacion</a>
    <br>
    {% for data in dataset %}
    
    {{ data.title }}</a><br/> 
    {{ data.description }}<br/> 
    <button><a href="{% url 'crud:update' data.id %}">Update</a></button>
    <button><a href="{% url 'crud:delete' data.id %}">Delete</a></button>
    <button><a href="{% url 'crud:detail' data.id  %}">Mas detalles</a></button>
    <hr/> 
    
  
    {% endfor %} 
  
</div> 

creacion/templates/update_view.html
<div class="main"> 
    <!-- Create a Form -->
    <form method="POST"> 
        <!-- Security token by Django -->
        {% csrf_token %} 
  
        <label for="Title">titulo </label>
        <input id="Title" value="{{titulo}}" name="titulo" type="text">
        <label for="descripcion">descripción </label>
        <input id="descripcion" value="{{descripcion}}" name="descripcion" type="text">
        <input type="submit" value="Update"> 
    </form> 
  
</div> 